# This Plugin depends on SDK modules and as such we need to build the whole SDK
# before being able to build this plugin.

name: Plugin Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'jMonkeyEngine/sdk'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for the scripts
      run: chmod +x gradlew *.sh
    
    - name: Download and Build the Engine
      run: ./build_engine.sh && ./fix_engine.sh
      
    - name: Build the SDK
      run: ./gradlew buildSdk
      
    - uses: actions/checkout@v2
      with:
        path: jme3-gui

    - name: Build the Plugin
      working-directory: jme3-gui
      run: ant
    
    - run: ls -lsh build/* release/* *
      working-directory: jme3-gui
