# This Plugin depends on SDK modules and as such we need to build the whole SDK
# before being able to build this plugin.

name: Plugin Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'jMonkeyEngine/sdk'
        ref: 'v3.3.0-beta1-sdkgradlepreview'

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for the scripts
      run: chmod +x gradlew *.sh
    
    - name: Download and Build the Engine
      run: TRAVIS=true TRAVIS_TAG=v3.3.0-beta1-sdkgradlepreview ./build_engine.sh && ./fix_engine.sh
      
    - name: Build the SDK
      run: ./gradlew buildSdk
    
    - name: Fix the SDK so we can build unsigned plugins
      run: sed -i "/keystore=.*/d" nbproject/platform.properties
      # This will delete the keystore= property, which would trigger asking for the signing secret in any case
      
    - uses: actions/checkout@v2
      with:
        path: jme3-nifty-gui

    - name: Build the Plugin
      working-directory: jme3-nifty-gui
      run: ant nbm-nosignature
    
    - name: Extract info.xml
      working-directory: jme3-nifty-gui
      run: unzip build/com-jme3-gde-gui.nbm 'Info/info.xml' && mv Info/info.xml info.xml
    
    - name: Fix info.xml
      working-directory: jme3-nifty-gui
      run: sed -i "s/downloadsize=\"0\"/downloadsize=\"$(wc -c <info.xml)\"/" info.xml

    - uses: actions/upload-artifact@v1
      with:
        name: com-jme3-gde-gui.nbm
        path: jme3-nifty-gui/build/com-jme3-gde-gui.nbm
        
    - uses: actions/upload-artifact@v1
      with:
        name: info.xml
        path: jme3-nifty-gui/info.xml
